"""Generate the Narwhals compatibility reference from its JSON source."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import TypedDict, cast


class MethodRecord(TypedDict):
    method: str
    arguments: str
    dtypes: str
    ordering: str
    since: str
    status: str
    notes: str


class CompatibilityMatrix(TypedDict):
    schema_version: int
    backend: str
    release: str
    methods: list[MethodRecord]


def load_matrix(path: Path) -> CompatibilityMatrix:
    """Load and minimally validate the machine-readable matrix."""
    decoded = cast("object", json.loads(path.read_text(encoding="utf-8")))
    if not isinstance(decoded, dict):
        raise ValueError("Compatibility matrix must be an object")
    raw = cast("dict[str, object]", decoded)
    if raw.get("schema_version") != 1:
        raise ValueError("Unsupported compatibility matrix schema")
    methods_value = raw.get("methods")
    if not isinstance(methods_value, list) or not methods_value:
        raise ValueError("Compatibility matrix must contain methods")
    methods = cast("list[object]", methods_value)
    required = {
        "method",
        "arguments",
        "dtypes",
        "ordering",
        "since",
        "status",
        "notes",
    }
    for value in methods:
        if not isinstance(value, dict):
            raise ValueError("Invalid compatibility method record")
        record = cast("dict[str, object]", value)
        if set(record) != required or not all(
            isinstance(record[key], str) for key in required
        ):
            raise ValueError("Invalid compatibility method record")
    return cast("CompatibilityMatrix", raw)


def render_matrix(matrix: CompatibilityMatrix) -> str:
    """Render a deterministic Markdown compatibility table."""
    lines = [
        "# Narwhals Compatibility",
        "",
        "<!-- Generated by scripts/generate_compatibility.py; do not edit. -->",
        "",
        f"Backend: `{matrix['backend']}` · Release: `{matrix['release']}`",
        "",
        "| Method | Arguments | Dtypes | Ordering | Since | Status | Notes |",
        "|---|---|---|---|---|---|---|",
    ]
    for record in matrix["methods"]:
        cells = [
            record["method"],
            record["arguments"],
            record["dtypes"],
            record["ordering"],
            record["since"],
            record["status"],
            record["notes"],
        ]
        escaped = [cell.replace("|", "\\|") for cell in cells]
        lines.append("| " + " | ".join(escaped) + " |")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check", action="store_true", help="fail if generated output is stale"
    )
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    source = root / "docs" / "narwhals-compatibility.json"
    destination = root / "docs" / "NARWHALS_COMPATIBILITY.md"
    rendered = render_matrix(load_matrix(source))
    if args.check:
        current = (
            destination.read_text(encoding="utf-8") if destination.exists() else None
        )
        if current != rendered:
            raise SystemExit("Generated Narwhals compatibility documentation is stale")
        return
    destination.write_text(rendered, encoding="utf-8")


if __name__ == "__main__":
    main()
