"""Build native or learned representations from generated synthetic market data.

Uses the market-data smoke dataset generated by ``demo/generate_market_data.py``.
The default workflow creates deterministic native two-channel representations.
``--provider tspulse`` runs the pinned optional TSPulse model over a bounded
univariate slice. ``--provider ts2vec`` verifies a locally trained multivariate
bundle and embeds bounded joint windows from the same dataset.
"""

from __future__ import annotations

import argparse
from collections.abc import Sequence
from datetime import datetime, timedelta
from pathlib import Path

import duckpd as pd

DEMO_DIR = Path(__file__).resolve().parent
DATASET = DEMO_DIR / "data" / "market-data-smoke.parquet"
TICKER = "NVDA"
WINDOW = 5
MATCHES = 5
TSPULSE_WINDOW = 512
TSPULSE_POINTS = 576
TSPULSE_BATCH_SIZE = 16
TS2VEC_CHANNELS = ("close_return", "bar_return", "intrabar_range")
TS2VEC_DEFAULT_BUNDLE = DEMO_DIR / ".tmp" / "ts2vec-market-smoke"
TS2VEC_BATCH_SIZE = 16


def _require_dataset() -> None:
    if not DATASET.exists():
        raise FileNotFoundError(
            f"Missing {DATASET}. Generate it with: uv run python demo/generate_market_data.py smoke"
        )


def run_native() -> None:
    """Run the lightweight deterministic native representation workflow."""
    representation = pd.series_representation(
        window=WINDOW,
        channels=("bar_return", "intrabar_range"),
        sampling="observations",
        data_contract="demo/ohlc-shape/v1",
        normalization="center",
        unit_norm=True,
        zero_scale="null",
    )

    with pd.connect() as session:
        # Grouped rolling windows require a declared chronological order.
        prices = session.read_parquet(
            DATASET,
            order_by=["ticker", "datetime"],
        )
        features = prices.assign(
            bar_return=lambda frame: (frame["close"] - frame["open"]) / frame["open"],
            intrabar_range=lambda frame: (frame["high"] - frame["low"]) / frame["open"],
        )
        windows = features.assign(
            return_window=lambda frame: (
                frame.groupby("ticker")["bar_return"].rolling(WINDOW).to_array()
            ),
            range_window=lambda frame: (
                frame.groupby("ticker")["intrabar_range"].rolling(WINDOW).to_array()
            ),
        )

        embedded = windows.embed_series(
            columns={
                "bar_return": "return_window",
                "intrabar_range": "range_window",
            },
            into="market_shape",
            representation=representation,
        )

        print(f"Dataset: {DATASET.name}")
        print(f"Representation: {representation.fingerprint}")
        print(f"Output type: FLOAT[{representation.dimension}]")
        print(f"Executions after planning: {session.execution_count}")

        # Warm-up rows have null representations. Use the raw channel windows
        # behind the first complete NVDA representation as a query-by-example.
        candidates = embedded[(embedded["ticker"] == TICKER) & embedded["market_shape"].notna()]
        query_row = candidates[["datetime", "return_window", "range_window"]].head(1)
        query = {
            "bar_return": tuple(float(value) for value in query_row.iloc[0]["return_window"]),
            "intrabar_range": tuple(float(value) for value in query_row.iloc[0]["range_window"]),
        }

        nearest = candidates.vector.search_series(
            query,
            column="market_shape",
            representation=representation,
            metric="l2",
            k=MATCHES,
            tie_breaker="datetime",
        )[
            [
                "datetime",
                "close",
                "bar_return",
                "intrabar_range",
                "market_shape",
                "_distance",
            ]
        ]

        print(f"\nQuery: first complete {TICKER} {WINDOW}-bar market-shape window")
        print(f"Query endpoint: {query_row.iloc[0]['datetime']}")  # pyright: ignore[reportUnknownMemberType]
        print(f"Query observations: {query}")
        print("\nNearest exact representations:")
        print(nearest.collect().to_string(index=False))  # pyright: ignore[reportUnknownMemberType]
        print(f"\nTotal executions: {session.execution_count}")


def run_tspulse() -> None:
    """Run the pinned TSPulse provider over a bounded slice of the smoke dataset."""
    encoder = pd.tspulse_series_embedding_model("bar_return")
    representation = pd.series_representation(
        window=TSPULSE_WINDOW,
        channels=("bar_return",),
        sampling="observations",
        data_contract="demo/ohlc-bar-return/tspulse-v1",
        encoder=encoder,
    )
    cutoff = datetime(2020, 1, 1) + timedelta(seconds=TSPULSE_POINTS)

    with pd.connect() as session:
        prepared = session.prepare_series_embedding_model(encoder)
        prices = session.read_parquet(
            DATASET,
            order_by=["ticker", "datetime"],
        )
        bounded = prices[(prices["ticker"] == TICKER) & (prices["datetime"] < cutoff)]
        features = bounded.assign(
            bar_return=lambda frame: (frame["close"] - frame["open"]) / frame["open"]
        )
        windows = features.assign(
            return_window=lambda frame: frame["bar_return"].rolling(TSPULSE_WINDOW).to_array()
        )
        embedded = windows.embed_series(
            columns={"bar_return": "return_window"},
            into="tspulse_embedding",
            representation=representation,
            batch_size=TSPULSE_BATCH_SIZE,
        )
        candidates = embedded[embedded["tspulse_embedding"].notna()]
        query_frame = features[["bar_return"]].head(TSPULSE_WINDOW)
        query = {"bar_return": tuple(float(value) for value in query_frame["bar_return"])}
        nearest = candidates.vector.search_series(
            query,
            column="tspulse_embedding",
            representation=representation,
            metric="cosine",
            k=MATCHES,
            tie_breaker="datetime",
        )[["datetime", "close", "bar_return", "_distance"]]

        print(f"Dataset: {DATASET.name}")
        print(f"Provider: {prepared.backend} on {prepared.execution_providers[0]}")
        print(f"Representation: {representation.fingerprint}")
        print(f"Output type: FLOAT[{representation.dimension}]")
        print(f"Input: first {TSPULSE_POINTS} {TICKER} bars")
        print("\nNearest exact TSPulse representations:")
        print(nearest.collect().to_string(index=False))  # pyright: ignore[reportUnknownMemberType]
        print(f"\nRuntime: {dict(prepared.runtime_versions)}")
        print(f"Total executions: {session.execution_count}")


def run_ts2vec(bundle_dir: Path) -> None:
    """Run one externally trained, attested TS2Vec bundle on the smoke dataset."""
    encoder = pd.ts2vec_series_embedding_model(bundle_dir)
    if encoder.input_channels != TS2VEC_CHANNELS:
        raise ValueError(
            "this demo requires TS2Vec channels "
            f"{TS2VEC_CHANNELS}; bundle declares {encoder.input_channels}"
        )
    representation = pd.series_representation(
        window=encoder.input_length,
        channels=encoder.input_channels,
        sampling="observations",
        data_contract="demo/synthetic-ohlc/ts2vec-v1",
        encoder=encoder,
    )
    input_points = encoder.input_length + 65
    cutoff = datetime(2020, 1, 1) + timedelta(seconds=input_points)

    with pd.connect() as session:
        prepared = session.prepare_series_embedding_model(
            encoder,
            artifact_dir=bundle_dir,
        )
        prices = session.read_parquet(
            DATASET,
            order_by=["ticker", "datetime"],
        )
        bounded = prices[(prices["ticker"] == TICKER) & (prices["datetime"] < cutoff)]
        features = bounded.assign(
            close_return=lambda frame: frame["close"].pct_change(),
            bar_return=lambda frame: (frame["close"] - frame["open"]) / frame["open"],
            intrabar_range=lambda frame: (frame["high"] - frame["low"]) / frame["open"],
        )
        windows = features.assign(
            close_return_window=lambda frame: (
                frame["close_return"].rolling(encoder.input_length).to_array()
            ),
            bar_return_window=lambda frame: (
                frame["bar_return"].rolling(encoder.input_length).to_array()
            ),
            intrabar_range_window=lambda frame: (
                frame["intrabar_range"].rolling(encoder.input_length).to_array()
            ),
        )
        embedded = windows.embed_series(
            columns={
                "close_return": "close_return_window",
                "bar_return": "bar_return_window",
                "intrabar_range": "intrabar_range_window",
            },
            into="ts2vec_embedding",
            representation=representation,
            batch_size=TS2VEC_BATCH_SIZE,
        )
        candidates = embedded[embedded["ts2vec_embedding"].notna()]
        query_source = features[features["close_return"].notna()]
        query_frame = query_source[["close_return", "bar_return", "intrabar_range"]].head(
            encoder.input_length
        )
        query = {
            channel: tuple(float(value) for value in query_frame[channel])
            for channel in TS2VEC_CHANNELS
        }
        nearest = candidates.vector.search_series(
            query,
            column="ts2vec_embedding",
            representation=representation,
            metric="cosine",
            k=MATCHES,
            tie_breaker="datetime",
        )[["datetime", "close", "close_return", "_distance"]]

        print(f"Dataset: {DATASET.name}")
        print(f"Provider: {prepared.backend} on {prepared.execution_providers[0]}")
        print(f"Bundle: {bundle_dir}")
        print(f"Representation: {representation.fingerprint}")
        print(f"Output type: FLOAT[{representation.dimension}]")
        print(f"Input: first {input_points} {TICKER} bars")
        print("\nNearest exact TS2Vec representations:")
        print(nearest.collect().to_string(index=False))  # pyright: ignore[reportUnknownMemberType]
        print(f"\nRuntime: {dict(prepared.runtime_versions)}")
        print(f"Total executions: {session.execution_count}")


def parse_args(argv: Sequence[str] | None = None) -> tuple[str, Path]:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--provider",
        choices=("native", "tspulse", "ts2vec"),
        default="native",
        help="optional learned providers require their matching DuckPD extra",
    )
    parser.add_argument(
        "--artifact-dir",
        type=Path,
        default=TS2VEC_DEFAULT_BUNDLE,
        help="attested local TS2Vec bundle used with --provider ts2vec",
    )
    namespace = parser.parse_args(argv)
    return str(namespace.provider), Path(namespace.artifact_dir)


def main(argv: Sequence[str] | None = None) -> None:
    _require_dataset()
    provider, artifact_dir = parse_args(argv)
    if provider == "tspulse":
        run_tspulse()
    elif provider == "ts2vec":
        run_ts2vec(artifact_dir)
    else:
        run_native()


if __name__ == "__main__":
    main()
