"""Build deterministic native time-series representations without a model runtime.

Uses the market-data smoke dataset generated by ``demo/generate_market_data.py``.
The workflow creates grouped fixed-count windows, normalizes and flattens two
channels with ``DataFrame.embed_series()``, then searches the resulting vectors
with DuckPD's exact vector engine.
"""

from __future__ import annotations

from pathlib import Path

import duckpd as pd

DEMO_DIR = Path(__file__).resolve().parent
DATASET = DEMO_DIR / "data" / "market-data-smoke.parquet"
TICKER = "NVDA"
WINDOW = 5
MATCHES = 5


def main() -> None:
    if not DATASET.exists():
        raise FileNotFoundError(
            f"Missing {DATASET}. Generate it with: uv run python demo/generate_market_data.py smoke"
        )

    representation = pd.series_representation(
        window=WINDOW,
        channels=("bar_return", "intrabar_range"),
        sampling="observations",
        data_contract="demo/ohlc-shape/v1",
        normalization="center",
        unit_norm=True,
        zero_scale="null",
    )

    with pd.connect() as session:
        # Grouped rolling windows require a declared chronological order.
        prices = session.read_parquet(
            DATASET,
            order_by=["ticker", "datetime"],
        )
        features = prices.assign(
            bar_return=lambda frame: (frame["close"] - frame["open"]) / frame["open"],
            intrabar_range=lambda frame: (frame["high"] - frame["low"]) / frame["open"],
        )
        windows = features.assign(
            return_window=lambda frame: (
                frame.groupby("ticker")["bar_return"].rolling(WINDOW).to_array()
            ),
            range_window=lambda frame: (
                frame.groupby("ticker")["intrabar_range"].rolling(WINDOW).to_array()
            ),
        )

        embedded = windows.embed_series(
            columns={
                "bar_return": "return_window",
                "intrabar_range": "range_window",
            },
            into="market_shape",
            representation=representation,
        )

        print(f"Dataset: {DATASET.name}")
        print(f"Representation: {representation.fingerprint}")
        print(f"Output type: FLOAT[{representation.dimension}]")
        print(f"Executions after planning: {session.execution_count}")

        # Warm-up rows have null representations. Use the raw channel windows
        # behind the first complete NVDA representation as a query-by-example.
        candidates = embedded[(embedded["ticker"] == TICKER) & embedded["market_shape"].notna()]
        query_row = candidates[["datetime", "return_window", "range_window"]].head(1)
        query = {
            "bar_return": tuple(float(value) for value in query_row.iloc[0]["return_window"]),
            "intrabar_range": tuple(float(value) for value in query_row.iloc[0]["range_window"]),
        }

        nearest = candidates.vector.search_series(
            query,
            column="market_shape",
            representation=representation,
            metric="l2",
            k=MATCHES,
            tie_breaker="datetime",
        )[
            [
                "datetime",
                "close",
                "bar_return",
                "intrabar_range",
                "market_shape",
                "_distance",
            ]
        ]

        print(f"\nQuery: first complete {TICKER} {WINDOW}-bar market-shape window")
        print(f"Query endpoint: {query_row.iloc[0]['datetime']}")  # pyright: ignore[reportUnknownMemberType]
        print(f"Query observations: {query}")
        print("\nNearest exact representations:")
        print(nearest.collect().to_string(index=False))  # pyright: ignore[reportUnknownMemberType]
        print(f"\nTotal executions: {session.execution_count}")


if __name__ == "__main__":
    main()
